import { Fuzzy_Bubbles } from "next/font/google";
import "./globals.css";
import BubblesAnimation from "../../components/bubblesanim";

const bubbles = Fuzzy_Bubbles({
  weight: ["400", "700"],
  variable: "--font-fuzzy-bubbles",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="overflow-x-hidden">
      <meta name="theme-color" content="#D16BFF" />
      <body
        className={`${bubbles.variable} font-fuzzy antialiased bg-gradient-to-r from-pink-500 via-purple-500 to-blue-500 relative overflow-x-hidden overflow-y-auto`}
      >
        <h1 className="text-[59px] text-center mt-10  font-extrabold bg-clip-text text-transparent bg-gradient-to-r from-yellow-500 to-pink-500 drop-shadow-2xl animate-bounce">
          BUBBLER
        </h1>
        <BubblesAnimation count={25} />

        <main>{children}</main>
      </body>
      <BubblesAnimation count={25} />
    </html>
  );
}
