import { Fuzzy_Bubbles } from "next/font/google";
import "./globals.css";
import BubblesAnimation from "../../components/bubblesanim";

const bubbles = Fuzzy_Bubbles({
  weight: ["400", "700"],
  variable: "--font-fuzzy-bubbles",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="overflow-x-hidden">
      <meta name="theme-color" content="#D16BFF" />
      <body
        className={`${bubbles.variable} min-h-screen  font-fuzzy antialiased bg-gradient-to-r from-pink-500 via-purple-500 to-blue-500 relative overflow-x-hidden overflow-y-auto`}
      >
        <BubblesAnimation count={100} />

        {/* Sticky Header with Transparency */}
        <header className="sticky top-0 z-50 bg-black bg-opacity-30 text-white p-4 sm:p-6 md:p-8 text-center h-16 sm:h-24 md:h-20 shadow-lg w-full">
          <h1 className="text-2xl sm:text-3xl md:text-4xl font-extrabold bg-clip-text text-transparent bg-gradient-to-r from-yellow-500 to-pink-500 drop-shadow-2xl animate-bounce">
            BUBBLER
          </h1>
        </header>

        {/* Content section */}
        <main className="mt-16">{children}</main>
      </body>
    </html>
  );
}
